### ISSUE TITLE
[Server] Add a 'Cordova' app type to the api server

### ISSUE THREAD

**Issue by david-martin** [feedhenry/mobile-control-panel#13]
Currently only `android` and `ios` are valid clientType's.

`cordova` should be a valid clientType, and show the cordova icon in the UI.
Valid app types are defined here https://github.com/feedhenry/mobile-control-panel/blob/2280946c0c3430aabeb0436ac1671878a3343e88/server/pkg/registry/mobileapp/strategy.go#L66

The 'Create Mobile App' screen will likely need updating for the type dropdown.
https://github.com/feedhenry/mobile-control-panel/blob/2280946c0c3430aabeb0436ac1671878a3343e88/ui/public/mcp.js#L124-L132

A ServiceClass should be added for a 'Cordova App' as well so it shows up in the service catalog similar to 'Android App' and 'iOS App'.
https://github.com/feedhenry/mobile-control-panel/blob/2280946c0c3430aabeb0436ac1671878a3343e88/server/pkg/mobile/broker/operations/catalog.go#L37

**Comment by vikramnr** [comment]
@david-martin  Can I try this one?

**Comment by david-martin** [comment]
@vikramnr sure, work away. Thanks

**Comment by david-martin** [comment]
@vikramnr If you're still thinking of taking this on and need any help or pointers, just shout

**Comment by vikramnr** [comment]
Apologies. I can't make any progress till 16 August. Is that fine?

**Comment by david-martin** [comment]
@vikramnr Sure, we can leave this for you unless the priority jumps

**Comment by vikramnr** [comment]
@david-martin  Is there an icon named as `Cordova` for drop down or should I add that one?

**Comment by david-martin** [comment]
@vikramnr I don't see a cordova or phonegap icon in font awesome. You can either add it, or use the 'mobile' icon for now.

**Comment by vikramnr** [comment]
@aidenkeating working on this?

**Comment by aidenkeating** [comment]
@vikramnr Nope I'm not

For some reason those two commits from your last PR got included again when I did a squash and merge of my PR. It didn't cause any issues or anything but I've ensured that it can't happen again just in case.

Feel free to continue on this.

**Comment by vikramnr** [comment]
Okay

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by david-martin** [comment]
@vikramnr I've added, among other icons, the cordova icon in #31. The `icon-cordova` class can be used.

Looks like there's an issue with the create new mobileapp screen for Cordova type. Probably just a case issue with Cordova vs. cordova. 
I'll fix that up later if you can't get around to it

**Comment by vikramnr** [comment]
@david-martin   
> I've added, among other icons, the cordova icon in #31. The icon-cordova class can be used.

I'll make changes to use the class  `icon-cordova`.  

>Looks like there's an issue with the create new mobileapp screen for Cordova type. Probably just a case issue with Cordova vs. cordova.

I'll take a look at this and revert back for any queries.

**Comment by vikramnr** [comment]
> Add a 'Cordova' app type to the api server to [Server] Add a 'Cordova' app type to the api server 2 days ago

@david-martin  So it should be added to `services[0]` then?

**Comment by david-martin** [comment]
@vikramnr Thats it, yes.
There are 2 ways of creating an App.

* from the Service Catalog
* from the Mobile UI

The later is already done for Cordova i.e. the Angularjs changes.
So its the catalog that needs a new ServiceClass for Cordova now.

Does that make sense?

**Comment by vikramnr** [comment]
@david-martin  Yep. I'll give it a try.

**Comment by maleck13** [comment]
closing as done. We have moved to a new repo https://github.com/feedhenry/mcp-standalone
