### ISSUE TITLE
[Server] Remove the 'App Type' parameter from the create step in the Service Catalog view

### ISSUE THREAD

**Issue by david-martin** [feedhenry/mobile-control-panel#16]
This parameter should be implied by choosing the Android or iOS app type from the catalog.
There is no need to expose or allow changing this parameter when going through the create flow
![image](https://user-images.githubusercontent.com/878251/28977373-c4cb4770-790f-11e7-98e7-1a6f36d0efc7.png)

The ServiceClass parameters are defined like this
https://github.com/feedhenry/mobile-control-panel/blob/2280946c0c3430aabeb0436ac1671878a3343e88/server/pkg/mobile/broker/operations/catalog.go#L65-L69

The `provision` endpoint should know what the 'ServiceClass' being created is, and shouldn't need a parameter to say what type it is as well.
https://github.com/feedhenry/mobile-control-panel/blob/fab4961f4523fda5f9e18c2fd413951982a231c3/server/pkg/mobile/broker/operations/provision.go#L14

**Comment by maleck13** [comment]
no longer relevant
