### ISSUE TITLE
[Installer] Templates should be recreated during broker setup

### ISSUE THREAD

**Issue by aidenkeating** [feedhenry/mobile-control-panel#35]
Currently when the template service broker is being setup, a resource will be skipped if one with the same name already exists.

https://github.com/feedhenry/mobile-control-panel/blob/49c98d74c4504b91674643bff434fef85af93abb/installer/roles/template-service-broker-setup/tasks/main.yml#L13

This should be configurable, allowing it to be forced even if the resource already exists.

**Comment by maleck13** [comment]
Is this still valid for mcp-standalone?

**Comment by aidenkeating** [comment]
@maleck13 I don't think this has ended up becoming an issue, I'll close it
